spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  application:
    name:
      PAYMENT-SERVICE
server:
  port: 8082


eureka:
  client:
    service-url.defaultZone:
      http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG